/**
 * Phase 3B — admin panel strings (ru/en only). Loaded at module import
 * via side-effects so handlers can call `tr(lang, 'admin.btn_back')`.
 *
 * uz/fil/zh/th intentionally not provided here — admins know ru/en.
 * Falls back to en automatically through the i18n loader.
 */
import { registerStrings } from "../../../services/i18n.js";

registerStrings("ru", {
  admin: {
    panel_title: "⚙️ Админ-панель GOLDEN_CONNECT",
    section_platform: "📊 Платформа",
    metric_users: "Юзеров",
    metric_users_24h: "за день",
    metric_payments_week: "Оплат за неделю",
    metric_events_active: "Активных эфиров",
    metric_pending_refs: "Pending рефералов",
    btn_users: "👥 Юзеры",
    btn_payments: "💳 Платежи",
    btn_broadcast: "📨 Рассылка",
    btn_tree: "🌳 Дерево рефов",
    btn_events: "📅 События",
    btn_leads: "📋 Leads",
    btn_promo: "📣 Промо",
    btn_video: "🎥 Видео",
    btn_monitor: "📡 Мониторинг",
    btn_setup: "🔧 Setup",
    btn_export: "📤 Экспорт",
    btn_reminders: "⚙️ Напоминалки",
    btn_refresh: "🔄 Обновить",
    btn_close: "❌ Закрыть",
    btn_back: "← Назад",
    btn_create: "➕ Создать",
    btn_delete: "🗑️ Удалить",
    btn_toggle: "🔁 Toggle active",
    btn_edit: "✏️ Редактировать",
    btn_confirm: "✅ Подтвердить",
    btn_cancel: "❌ Отмена",
    btn_skip: "Пропустить",
    promo_title: "📣 Промо-шаблоны",
    video_title: "🎥 Видео-библиотека",
    monitor_title: "📡 Мониторинг чатов",
    only_admin: "Только для админа.",
    cancelled: "Отменено.",
    timed_out: "Сессия истекла. Начни заново.",
    not_found: "Не найдено.",
    deleted: "Удалено.",
    saved: "Сохранено.",
    error_generic: "Ошибка.",
  },
});

registerStrings("en", {
  admin: {
    panel_title: "⚙️ GOLDEN_CONNECT admin panel",
    section_platform: "📊 Platform",
    metric_users: "Users",
    metric_users_24h: "today",
    metric_payments_week: "Weekly payments",
    metric_events_active: "Active events",
    metric_pending_refs: "Pending referrals",
    btn_users: "👥 Users",
    btn_payments: "💳 Payments",
    btn_broadcast: "📨 Broadcast",
    btn_tree: "🌳 Ref tree",
    btn_events: "📅 Events",
    btn_leads: "📋 Leads",
    btn_promo: "📣 Promo",
    btn_video: "🎥 Videos",
    btn_monitor: "📡 Monitor",
    btn_setup: "🔧 Setup",
    btn_export: "📤 Export",
    btn_reminders: "⚙️ Reminders",
    btn_refresh: "🔄 Refresh",
    btn_close: "❌ Close",
    btn_back: "← Back",
    btn_create: "➕ Create",
    btn_delete: "🗑️ Delete",
    btn_toggle: "🔁 Toggle active",
    btn_edit: "✏️ Edit",
    btn_confirm: "✅ Confirm",
    btn_cancel: "❌ Cancel",
    btn_skip: "Skip",
    promo_title: "📣 Promo templates",
    video_title: "🎥 Video library",
    monitor_title: "📡 Monitored chats",
    only_admin: "Admin only.",
    cancelled: "Cancelled.",
    timed_out: "Session timed out. Start over.",
    not_found: "Not found.",
    deleted: "Deleted.",
    saved: "Saved.",
    error_generic: "Error.",
  },
});
