/**
 * i18n strings for the Phase 3A bot menu redesign.
 *
 * The new /start screen replaces the slim 3-button keyboard with a
 * full feature grid + a row of utility buttons (language picker, help).
 * Every label and command description in the TG hamburger menu lives
 * here as a `tr()` lookup so all 6 locales stay aligned.
 *
 * Side-effect import — registered once at module load. `tr()` falls
 * back to English when a locale is missing a key, but every locale
 * declared below carries the full set so QA shouldn't see the raw key.
 */
import { registerStrings } from "../../services/i18n.js";

registerStrings("ru", {
  menu: {
    main_title: "🏠 Главное меню GOLDEN_CONNECT",
    main_subtitle:
      "Выбирай раздел — все инструменты партнёра в одном месте.",
    btn_cabinet: "🚀 Открыть кабинет",
    btn_ref: "🔗 Реф-ссылка",
    btn_team: "👥 Команда",
    btn_quests: "🎯 Квесты",
    btn_missions: "📋 Миссии",
    btn_quiz: "🧪 Квизы",
    btn_top: "🏆 Топ",
    btn_events: "📅 Эфиры",
    btn_promo: "📣 Реклама",
    btn_video: "🎥 Видео",
    btn_stats: "📊 Статс",
    btn_lang: "🌍 Язык",
    btn_help: "❓ Помощь",
    btn_back: "← Назад",
    lang_picker_title: "🌍 Выбери язык / Choose language",
  },
  cmd_desc: {
    start: "🏠 Главное меню",
    app: "🚀 Открыть кабинет",
    ref: "🔗 Моя реф-ссылка",
    team: "👥 Моя команда",
    events: "📅 Эфиры и вебинары",
    quests: "🎯 Квесты",
    missions: "📋 Миссии партнёра",
    quiz: "🧪 Квизы",
    top: "🏆 Топ партнёров",
    promo: "📣 Реклама",
    scheduler: "📅 Планировщик постов",
    meet: "🎥 Видеоконференции",
    video: "🎥 Видео",
    balance: "💰 Баланс и финансы",
    tariffs: "💎 Тарифы",
    stats: "📊 Моя статистика",
    lang: "🌍 Язык",
    help: "❓ Справка",
  },
  help: {
    title: "❓ Команды бота",
    intro: "Жми кнопку или вводи команду — оба способа работают.",
    list_start: "🏠 /start — главное меню",
    list_app: "🚀 /app — кабинет (WebApp)",
    list_ref: "🔗 /ref — моя реф-ссылка",
    list_team: "👥 /team — моя команда",
    list_events: "📅 /events — эфиры и вебинары",
    list_quests: "🎯 /quests — квесты + XP",
    list_missions: "📋 /missions — 7-дневные миссии",
    list_quiz: "🧪 /quiz — подбор роли / тарифа",
    list_top: "🏆 /top — топ партнёров",
    list_promo: "📣 /promo — реклама (хаб: купить/заработать/промо)",
    list_scheduler: "📅 /scheduler — планировщик постов в TG",
    list_meet: "🎥 /meet — видеоконференции с командой",
    list_video: "🎥 /video — видео-библиотека",
    list_stats: "📊 /stats — моя статистика",
    list_lang: "🌍 /lang — сменить язык",
    list_help: "❓ /help — это сообщение",
  },
});

registerStrings("en", {
  menu: {
    main_title: "🏠 GOLDEN_CONNECT main menu",
    main_subtitle: "Pick a section — all partner tools in one place.",
    btn_cabinet: "🚀 Open cabinet",
    btn_ref: "🔗 Ref link",
    btn_team: "👥 Team",
    btn_quests: "🎯 Quests",
    btn_missions: "📋 Missions",
    btn_quiz: "🧪 Quizzes",
    btn_top: "🏆 Top",
    btn_events: "📅 Events",
    btn_promo: "📣 Promo",
    btn_video: "🎥 Video",
    btn_stats: "📊 Stats",
    btn_lang: "🌍 Language",
    btn_help: "❓ Help",
    btn_back: "← Back",
    lang_picker_title: "🌍 Choose language / Выбери язык",
  },
  cmd_desc: {
    start: "🏠 Main menu",
    app: "🚀 Open cabinet",
    ref: "🔗 My referral link",
    team: "👥 My team",
    events: "📅 Streams & webinars",
    quests: "🎯 Quests",
    missions: "📋 Partner missions",
    quiz: "🧪 Quizzes",
    top: "🏆 Top partners",
    promo: "📣 Promo & QR",
    video: "🎥 Video library",
    stats: "📊 My stats",
    lang: "🌍 Language",
    help: "❓ Help",
  },
  help: {
    title: "❓ Bot commands",
    intro: "Tap a button or type a command — both work.",
    list_start: "🏠 /start — main menu",
    list_app: "🚀 /app — cabinet (WebApp)",
    list_ref: "🔗 /ref — my referral link",
    list_team: "👥 /team — my team",
    list_events: "📅 /events — streams & webinars",
    list_quests: "🎯 /quests — quests + XP",
    list_missions: "📋 /missions — 7-day missions",
    list_quiz: "🧪 /quiz — pick a role / plan",
    list_top: "🏆 /top — top partners",
    list_promo: "📣 /promo — promo templates & QR",
    list_video: "🎥 /video — video library",
    list_stats: "📊 /stats — my stats",
    list_lang: "🌍 /lang — switch language",
    list_help: "❓ /help — this message",
  },
});

registerStrings("zh", {
  menu: {
    main_title: "🏠 GOLDEN_CONNECT 主菜单",
    main_subtitle: "选择栏目 —— 所有合作伙伴工具在一处。",
    btn_cabinet: "🚀 打开账户",
    btn_ref: "🔗 推荐链接",
    btn_team: "👥 团队",
    btn_quests: "🎯 任务",
    btn_missions: "📋 周计划",
    btn_quiz: "🧪 测验",
    btn_top: "🏆 排行",
    btn_events: "📅 直播",
    btn_promo: "📣 推广",
    btn_video: "🎥 视频",
    btn_stats: "📊 统计",
    btn_lang: "🌍 语言",
    btn_help: "❓ 帮助",
    btn_back: "← 返回",
    lang_picker_title: "🌍 选择语言 / Choose language",
  },
  cmd_desc: {
    start: "🏠 主菜单",
    app: "🚀 打开账户",
    ref: "🔗 我的推荐链接",
    team: "👥 我的团队",
    events: "📅 直播与网研会",
    quests: "🎯 任务",
    missions: "📋 合作伙伴周计划",
    quiz: "🧪 测验",
    top: "🏆 顶级合作伙伴",
    promo: "📣 推广与二维码",
    video: "🎥 视频库",
    stats: "📊 我的统计",
    lang: "🌍 语言",
    help: "❓ 帮助",
  },
  help: {
    title: "❓ 机器人命令",
    intro: "点击按钮或输入命令 —— 两种方式都行。",
    list_start: "🏠 /start — 主菜单",
    list_app: "🚀 /app — 账户 (WebApp)",
    list_ref: "🔗 /ref — 我的推荐链接",
    list_team: "👥 /team — 我的团队",
    list_events: "📅 /events — 直播与网研会",
    list_quests: "🎯 /quests — 任务 + XP",
    list_missions: "📋 /missions — 7 天周计划",
    list_quiz: "🧪 /quiz — 选择角色 / 套餐",
    list_top: "🏆 /top — 顶级合作伙伴",
    list_promo: "📣 /promo — 推广模板与二维码",
    list_video: "🎥 /video — 视频库",
    list_stats: "📊 /stats — 我的统计",
    list_lang: "🌍 /lang — 切换语言",
    list_help: "❓ /help — 此消息",
  },
});

registerStrings("uz", {
  menu: {
    main_title: "🏠 GOLDEN_CONNECT bosh menyu",
    main_subtitle: "Bo'limni tanlang — barcha hamkor vositalari bir joyda.",
    btn_cabinet: "🚀 Kabinetni ochish",
    btn_ref: "🔗 Ref havola",
    btn_team: "👥 Jamoa",
    btn_quests: "🎯 Kvestlar",
    btn_missions: "📋 Missiyalar",
    btn_quiz: "🧪 Viktorinalar",
    btn_top: "🏆 Top",
    btn_events: "📅 Efirlar",
    btn_promo: "📣 Reklama",
    btn_video: "🎥 Video",
    btn_stats: "📊 Statistika",
    btn_lang: "🌍 Til",
    btn_help: "❓ Yordam",
    btn_back: "← Orqaga",
    lang_picker_title: "🌍 Tilni tanlang / Choose language",
  },
  cmd_desc: {
    start: "🏠 Bosh menyu",
    app: "🚀 Kabinetni ochish",
    ref: "🔗 Mening ref havolam",
    team: "👥 Mening jamoam",
    events: "📅 Efirlar va vebinarlar",
    quests: "🎯 Kvestlar",
    missions: "📋 Hamkor missiyalari",
    quiz: "🧪 Viktorinalar",
    top: "🏆 Top hamkorlar",
    promo: "📣 Reklama va QR",
    video: "🎥 Video kutubxona",
    stats: "📊 Mening statistikam",
    lang: "🌍 Til",
    help: "❓ Yordam",
  },
  help: {
    title: "❓ Bot buyruqlari",
    intro: "Tugmani bosing yoki buyruqni yozing — ikkalasi ham ishlaydi.",
    list_start: "🏠 /start — bosh menyu",
    list_app: "🚀 /app — kabinet (WebApp)",
    list_ref: "🔗 /ref — mening ref havolam",
    list_team: "👥 /team — mening jamoam",
    list_events: "📅 /events — efirlar va vebinarlar",
    list_quests: "🎯 /quests — kvestlar + XP",
    list_missions: "📋 /missions — 7 kunlik missiyalar",
    list_quiz: "🧪 /quiz — rol / tarifni tanlash",
    list_top: "🏆 /top — top hamkorlar",
    list_promo: "📣 /promo — reklama shablonlari va QR",
    list_video: "🎥 /video — video kutubxona",
    list_stats: "📊 /stats — mening statistikam",
    list_lang: "🌍 /lang — tilni almashtirish",
    list_help: "❓ /help — ushbu xabar",
  },
});

registerStrings("fil", {
  menu: {
    main_title: "🏠 GOLDEN_CONNECT main menu",
    main_subtitle: "Pumili ng seksyon — lahat ng partner tools sa isang lugar.",
    btn_cabinet: "🚀 Buksan ang kabinet",
    btn_ref: "🔗 Ref link",
    btn_team: "👥 Team",
    btn_quests: "🎯 Quests",
    btn_missions: "📋 Missions",
    btn_quiz: "🧪 Mga quiz",
    btn_top: "🏆 Top",
    btn_events: "📅 Mga event",
    btn_promo: "📣 Promo",
    btn_video: "🎥 Video",
    btn_stats: "📊 Stats",
    btn_lang: "🌍 Wika",
    btn_help: "❓ Tulong",
    btn_back: "← Balik",
    lang_picker_title: "🌍 Pumili ng wika / Choose language",
  },
  cmd_desc: {
    start: "🏠 Pangunahing menu",
    app: "🚀 Buksan ang kabinet",
    ref: "🔗 Aking referral link",
    team: "👥 Aking team",
    events: "📅 Mga stream at webinar",
    quests: "🎯 Mga quest",
    missions: "📋 Mga partner mission",
    quiz: "🧪 Mga quiz",
    top: "🏆 Mga top partner",
    promo: "📣 Promo at QR",
    video: "🎥 Video library",
    stats: "📊 Aking stats",
    lang: "🌍 Wika",
    help: "❓ Tulong",
  },
  help: {
    title: "❓ Mga utos ng bot",
    intro: "Pindutin ang button o i-type ang utos — pareho gumagana.",
    list_start: "🏠 /start — pangunahing menu",
    list_app: "🚀 /app — kabinet (WebApp)",
    list_ref: "🔗 /ref — aking referral link",
    list_team: "👥 /team — aking team",
    list_events: "📅 /events — mga stream at webinar",
    list_quests: "🎯 /quests — mga quest + XP",
    list_missions: "📋 /missions — 7-araw na missions",
    list_quiz: "🧪 /quiz — pumili ng role / plan",
    list_top: "🏆 /top — mga top partner",
    list_promo: "📣 /promo — promo templates at QR",
    list_video: "🎥 /video — video library",
    list_stats: "📊 /stats — aking stats",
    list_lang: "🌍 /lang — palitan ang wika",
    list_help: "❓ /help — ang mensaheng ito",
  },
});

registerStrings("th", {
  menu: {
    main_title: "🏠 เมนูหลัก GOLDEN_CONNECT",
    main_subtitle: "เลือกหมวด — เครื่องมือพาร์ทเนอร์ทั้งหมดในที่เดียว",
    btn_cabinet: "🚀 เปิดบัญชี",
    btn_ref: "🔗 ลิงก์แนะนำ",
    btn_team: "👥 ทีม",
    btn_quests: "🎯 เควสต์",
    btn_missions: "📋 ภารกิจ",
    btn_quiz: "🧪 แบบทดสอบ",
    btn_top: "🏆 อันดับ",
    btn_events: "📅 ไลฟ์",
    btn_promo: "📣 โปรโม",
    btn_video: "🎥 วิดีโอ",
    btn_stats: "📊 สถิติ",
    btn_lang: "🌍 ภาษา",
    btn_help: "❓ ช่วยเหลือ",
    btn_back: "← ย้อนกลับ",
    lang_picker_title: "🌍 เลือกภาษา / Choose language",
  },
  cmd_desc: {
    start: "🏠 เมนูหลัก",
    app: "🚀 เปิดบัญชี",
    ref: "🔗 ลิงก์แนะนำของฉัน",
    team: "👥 ทีมของฉัน",
    events: "📅 ไลฟ์และเว็บบินาร์",
    quests: "🎯 เควสต์",
    missions: "📋 ภารกิจพาร์ทเนอร์",
    quiz: "🧪 แบบทดสอบ",
    top: "🏆 พาร์ทเนอร์อันดับต้น",
    promo: "📣 โปรโมและ QR",
    video: "🎥 คลังวิดีโอ",
    stats: "📊 สถิติของฉัน",
    lang: "🌍 ภาษา",
    help: "❓ ช่วยเหลือ",
  },
  help: {
    title: "❓ คำสั่งของบอท",
    intro: "กดปุ่มหรือพิมพ์คำสั่ง — ใช้ได้ทั้งสองวิธี",
    list_start: "🏠 /start — เมนูหลัก",
    list_app: "🚀 /app — บัญชี (WebApp)",
    list_ref: "🔗 /ref — ลิงก์แนะนำของฉัน",
    list_team: "👥 /team — ทีมของฉัน",
    list_events: "📅 /events — ไลฟ์และเว็บบินาร์",
    list_quests: "🎯 /quests — เควสต์ + XP",
    list_missions: "📋 /missions — ภารกิจ 7 วัน",
    list_quiz: "🧪 /quiz — เลือกบทบาท / แพ็กเกจ",
    list_top: "🏆 /top — พาร์ทเนอร์อันดับต้น",
    list_promo: "📣 /promo — เทมเพลตโปรโมและ QR",
    list_video: "🎥 /video — คลังวิดีโอ",
    list_stats: "📊 /stats — สถิติของฉัน",
    list_lang: "🌍 /lang — เปลี่ยนภาษา",
    list_help: "❓ /help — ข้อความนี้",
  },
});
