/**
 * i18n strings for /ref and /team flows (Phase 1A).
 *
 * Copy voice: TrendeX — advertising ecosystem with 3 roles (business, users,
 * partners). Tone follows start.ts / presentation.ts — friendly, "ты" in RU,
 * business-oriented, motivating without MLM clichés. Loaded once at module
 * import (side-effect). `tr()` falls back to en when the locale is missing,
 * so only ru + en are registered here.
 */
import { registerStrings } from "../../services/i18n.js";

registerStrings("ru", {
  referral: {
    title: "🤝 Твоя партнёрская ссылка",
    link_intro: "Делись — каждый приглашённый растит твою команду:",
    stats_line:
      "В команде: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid}",
    badges_line: "XP и бейджи: 🏆 <b>{count}</b>",
    challenges_line: "⚡ Активных челленджей: <b>{active}</b>",
    list_title: "📋 Мои рефералы",
    list_empty:
      "Пока никто не перешёл по ссылке. Скинь её паре друзей — и команда пойдёт в рост 🚀",
    list_empty_promo_intro: "<b>📢 Готовые посты — копируй и публикуй:</b>",
    promo_short:
      "🚀 Заработок на рекламе в Trendex — проверенный сервис. Регистрация по моей ссылке: {link}",
    promo_medium:
      "💼 Заходи в Trendex — рекламная экосистема с долей прибыли.\n\n• 4 баланса (рабочий/подарочный/подписочный/карма)\n• 10 уровней реферальной программы\n• Розыгрыш $100/неделя\n• Старт от $45\n\nПодключайся: {link}",
    promo_long:
      "🎯 Открыл для себя Trendex — площадку, где рекламодатели платят пользователям и партнёрам.\n\nЧто получаю:\n✓ До $50/день за активность даже на FREE\n✓ 10% с каждого приглашённого + до 10 уровней\n✓ Карма-розыгрыш $100 каждое воскресенье\n✓ Тарифы LAUNCH ($45) / BOOST ($90) / ROCKET ($135) — у каждого глубина матрицы и доходные места\n\nПрисоединяйся: {link}",
    promo_pack: "<b>📦 Промо-пак (текст + ссылка):</b>",
    promo_tip: "<i>💡 Лучше работает: личное сообщение «привет, посмотри что нашёл» + ссылка. Холодные посты в каналы — на втором месте.</i>",
    btn_copy_short: "📋 Короткий пост",
    btn_copy_medium: "📋 Средний пост",
    btn_copy_long: "📋 Длинный пост",
    btn_share_tg: "📤 Поделиться в Telegram",
    top_title: "📊 Топ партнёров (за 30 дней)",
    top_empty: "Таблица пока пустая. Будь первым — пригласи и займи место 🥇",
    btn_list: "📋 Мои рефералы",
    btn_badges: "🏆 Бейджи",
    btn_challenges: "⚡ Челленджи",
    btn_top: "📊 Топ партнёров",
    btn_back: "← Назад",
    btn_prev: "◀️ Назад",
    btn_next: "Вперёд ▶️",
    stage: {
      invited: "Приглашён",
      joined: "Зашёл в бот",
      active: "Активен",
      booked: "Забронировал тариф",
      paid: "Оплатил ✅",
      dormant: "Остыл ⚠️",
      lost: "Ушёл ⚫",
    },
  },
  team: {
    title: "👥 Моя команда",
    funnel_title: "Воронка",
    funnel_line:
      "Всего: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid} ⚠️{dormant} ⚫{lost}",
    next_title: "📌 Все задачи на сегодня",
    next_heading: "📌 Что сделать сегодня",
    next_empty: "Чисто — задач нет. Можно выдохнуть ☕️",
    recent_heading: "🆕 Недавние в команде:",
    snooze_ok: "⏱️ Отложено на 3 дня",
    snooze_not_found: "Задача уже закрыта или не найдена",
    done_ok: "✅ Готово",
    done_failed: "Не получилось — попробуй ещё раз",
    btn_done: "✅ {name}",
    btn_snooze: "⏱️",
    btn_all_actions: "📌 Все задачи",
    btn_ref_overview: "🤝 Реф-ссылка",
    btn_refresh: "🔄 Обновить",
    reason: {
      invited_no_join_24h: "не зашёл в бот за сутки — напомни",
      just_paid: "только что оплатил — поздравь 🎉",
      booked_silent_3d: "3 дня после брони — помоги довести до оплаты",
      active_silent_7d: "7 дней без активности — проверь, что происходит",
      winback_dormant: "пора вернуть — возможно тёплый возврат",
      joined_no_activity_7d: "зашёл, но не сделал ни шага — нужен онбординг",
    },
  },
  challenges: {
    title: "⚡ Челленджи партнёра",
    active_heading: "В процессе:",
    available_heading: "Доступны:",
    progress_line: "Прогресс: <b>{progress}/{goal}</b> · осталось {days} дн.",
    mark_active: "— уже идёт",
    mark_done: "— ✅ пройдено",
    btn_start: "▶️ Начать: {title}",
    started_toast: "⚡ Челлендж запущен! Погнали 🚀",
    start_failed_toast: "Уже активен или пока недоступен",
    t: {
      invite_3_in_7d: "Пригласи 3 человек за 7 дней",
      invite_5_in_14d: "Пригласи 5 человек за 14 дней",
      invite_10_in_30d: "Пригласи 10 человек за 30 дней",
    },
  },
  badges: {
    title: "🏆 Мои бейджи",
    empty:
      "Бейджей пока нет. Приведи первого оплатившего — и получишь 🎉 «Первая оплата в команде»",
    first_paid: "🎉 Первая оплата в команде",
    partner_5: "⭐ Партнёр 5+",
    partner_10: "🌟 Партнёр 10+",
    partner_25: "💎 Партнёр 25+",
    challenger_bronze: "🥉 Быстрый старт",
    challenger_silver: "🥈 Уверенный рост",
    challenger_gold: "🥇 Лидер команды",
  },
});

registerStrings("uz", {
  referral: {
    title: "🤝 Sizning hamkorlik havolangiz",
    link_intro: "Ulash — har bir qo'shilgan odam jamoangizni o'stiradi:",
    stats_line:
      "Jamoa: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid}",
    badges_line: "XP va nishonlar: 🏆 <b>{count}</b>",
    challenges_line: "⚡ Faol chellenjlar: <b>{active}</b>",
    list_title: "📋 Mening referallarim",
    list_empty:
      "Havola orqali hali hech kim qo'shilmadi. Bir-ikki do'stingizga yuboring — jamoa shu yerdan boshlanadi 🚀",
    top_title: "📊 Eng yaxshi hamkorlar (30 kun)",
    top_empty: "Jadval hali bo'sh. Birinchi bo'ling — taklif qiling va birinchi o'rinni egallang 🥇",
    btn_list: "📋 Referallarim",
    btn_badges: "🏆 Nishonlar",
    btn_challenges: "⚡ Chellenjlar",
    btn_top: "📊 Top hamkorlar",
    btn_back: "← Orqaga",
    btn_prev: "◀️ Oldingi",
    btn_next: "Keyingi ▶️",
    stage: {
      invited: "Taklif qilingan",
      joined: "Botga kirdi",
      active: "Faol",
      booked: "Tarif band qildi",
      paid: "To'ladi ✅",
      dormant: "Sovidi ⚠️",
      lost: "Ketdi ⚫",
    },
  },
  team: {
    title: "👥 Mening jamoam",
    funnel_title: "Voronka",
    funnel_line:
      "Jami: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid} ⚠️{dormant} ⚫{lost}",
    next_title: "📌 Bugungi barcha vazifalar",
    next_heading: "📌 Bugun nima qilish kerak",
    next_empty: "Hammasi joyida — vazifalar yo'q. Dam oling ☕️",
    recent_heading: "🆕 Jamoadagi yangilar:",
    snooze_ok: "⏱️ 3 kunga qoldirildi",
    snooze_not_found: "Vazifa allaqachon yopilgan yoki topilmadi",
    done_ok: "✅ Tayyor",
    done_failed: "Bo'lmadi — qayta urinib ko'ring",
    btn_done: "✅ {name}",
    btn_snooze: "⏱️",
    btn_all_actions: "📌 Barcha vazifalar",
    btn_ref_overview: "🤝 Ref havola",
    btn_refresh: "🔄 Yangilash",
    reason: {
      invited_no_join_24h: "24 soatda botga kirmadi — eslatma yuboring",
      just_paid: "endigina to'ladi — tabriklang 🎉",
      booked_silent_3d: "bronlashdan 3 kun — to'lovga yetaklang",
      active_silent_7d: "7 kun jim — nima bo'lganini tekshiring",
      winback_dormant: "qaytarish vaqti — iliq qaytish mumkin",
      joined_no_activity_7d:
        "kirgan, lekin hech qadam yo'q — onboarding kerak",
    },
  },
  challenges: {
    title: "⚡ Hamkor chellenjlari",
    active_heading: "Davom etmoqda:",
    available_heading: "Mavjud:",
    progress_line: "Natija: <b>{progress}/{goal}</b> · {days} kun qoldi",
    mark_active: "— davom etmoqda",
    mark_done: "— ✅ bajarildi",
    btn_start: "▶️ Boshlash: {title}",
    started_toast: "⚡ Chellenj boshlandi — ketdik 🚀",
    start_failed_toast: "Allaqachon faol yoki hali mavjud emas",
    t: {
      invite_3_in_7d: "7 kunda 3 kishini taklif qiling",
      invite_5_in_14d: "14 kunda 5 kishini taklif qiling",
      invite_10_in_30d: "30 kunda 10 kishini taklif qiling",
    },
  },
  badges: {
    title: "🏆 Mening nishonlarim",
    empty:
      "Hali nishonlar yo'q. Birinchi to'lovchi jamoadoshingizni keltiring — 🎉 «Jamoadagi birinchi to'lov» nishonini olasiz",
    first_paid: "🎉 Jamoadagi birinchi to'lov",
    partner_5: "⭐ Hamkor 5+",
    partner_10: "🌟 Hamkor 10+",
    partner_25: "💎 Hamkor 25+",
    challenger_bronze: "🥉 Tezkor start",
    challenger_silver: "🥈 Barqaror o'sish",
    challenger_gold: "🥇 Jamoa lideri",
  },
});

registerStrings("fil", {
  referral: {
    title: "🤝 Ang iyong partner link",
    link_intro: "Ibahagi — bawat sign-up ay nagpapalago sa team mo:",
    stats_line:
      "Team: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid}",
    badges_line: "XP at badges: 🏆 <b>{count}</b>",
    challenges_line: "⚡ Aktibong challenges: <b>{active}</b>",
    list_title: "📋 Mga referral ko",
    list_empty:
      "Wala pang sumali sa link mo. I-share sa ilang kaibigan — dito nagsisimula ang team mo 🚀",
    top_title: "📊 Top partners (huling 30 araw)",
    top_empty: "Walang laman pa ang leaderboard. Maging una — mag-invite at agawin ang tuktok 🥇",
    btn_list: "📋 Mga referral",
    btn_badges: "🏆 Badges",
    btn_challenges: "⚡ Challenges",
    btn_top: "📊 Top partners",
    btn_back: "← Balik",
    btn_prev: "◀️ Prev",
    btn_next: "Susunod ▶️",
    stage: {
      invited: "Inimbitahan",
      joined: "Sumali sa bot",
      active: "Aktibo",
      booked: "Nag-book ng plano",
      paid: "Bayad na ✅",
      dormant: "Lumamig ⚠️",
      lost: "Nawala ⚫",
    },
  },
  team: {
    title: "👥 Aking team",
    funnel_title: "Funnel",
    funnel_line:
      "Kabuuan: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid} ⚠️{dormant} ⚫{lost}",
    next_title: "📌 Lahat ng tasks ngayong araw",
    next_heading: "📌 Gawin ngayong araw",
    next_empty: "Wala nang task — huminga muna ☕️",
    recent_heading: "🆕 Bago sa team mo:",
    snooze_ok: "⏱️ Ipinagpaliban ng 3 araw",
    snooze_not_found: "Sarado na o hindi nahanap ang task",
    done_ok: "✅ Tapos na",
    done_failed: "Hindi gumana — subukan ulit",
    btn_done: "✅ {name}",
    btn_snooze: "⏱️",
    btn_all_actions: "📌 Lahat ng tasks",
    btn_ref_overview: "🤝 Ref link",
    btn_refresh: "🔄 I-refresh",
    reason: {
      invited_no_join_24h: "24 oras na hindi bumubukas — magpadala ng reminder",
      just_paid: "kabayad lang — batiin 🎉",
      booked_silent_3d: "3 araw matapos mag-book — tulungan mag-bayad",
      active_silent_7d: "7 araw nang tahimik — alamin ang nangyayari",
      winback_dormant: "oras para ibalik — mainit na balik ay posible",
      joined_no_activity_7d:
        "sumali pero walang hakbang — kailangan ng onboarding",
    },
  },
  challenges: {
    title: "⚡ Mga challenge ng partner",
    active_heading: "Kasalukuyan:",
    available_heading: "Available:",
    progress_line: "Progress: <b>{progress}/{goal}</b> · {days} araw na lang",
    mark_active: "— kasalukuyan",
    mark_done: "— ✅ tapos na",
    btn_start: "▶️ Simulan: {title}",
    started_toast: "⚡ Nagsimula ang challenge — tara 🚀",
    start_failed_toast: "Aktibo na o hindi pa available",
    t: {
      invite_3_in_7d: "Mag-invite ng 3 sa loob ng 7 araw",
      invite_5_in_14d: "Mag-invite ng 5 sa loob ng 14 araw",
      invite_10_in_30d: "Mag-invite ng 10 sa loob ng 30 araw",
    },
  },
  badges: {
    title: "🏆 Aking mga badge",
    empty:
      "Wala pang badge. Magdala ng unang bayad na kasama — at makakakuha ka ng 🎉 «First payment in team»",
    first_paid: "🎉 Unang bayad sa team",
    partner_5: "⭐ Partner 5+",
    partner_10: "🌟 Partner 10+",
    partner_25: "💎 Partner 25+",
    challenger_bronze: "🥉 Mabilis na simula",
    challenger_silver: "🥈 Matatag na paglago",
    challenger_gold: "🥇 Team leader",
  },
});

registerStrings("th", {
  referral: {
    title: "🤝 ลิงก์พาร์ทเนอร์ของคุณ",
    link_intro: "แชร์เลย — ทุกคนที่สมัครผ่านลิงก์จะช่วยขยายทีมของคุณ:",
    stats_line:
      "ทีม: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid}",
    badges_line: "XP และเหรียญ: 🏆 <b>{count}</b>",
    challenges_line: "⚡ ชาเลนจ์ที่กำลังทำ: <b>{active}</b>",
    list_title: "📋 รายชื่อคนที่คุณแนะนำ",
    list_empty:
      "ยังไม่มีใครสมัครผ่านลิงก์ของคุณ ลองส่งให้เพื่อนสักสองสามคน — ทีมเริ่มต้นที่นี่ 🚀",
    top_title: "📊 พาร์ทเนอร์อันดับต้น (30 วันล่าสุด)",
    top_empty: "ลีดเดอร์บอร์ดยังว่างอยู่ มาเป็นคนแรก — ชวนเพื่อนแล้วคว้าอันดับ 🥇",
    btn_list: "📋 คนที่แนะนำ",
    btn_badges: "🏆 เหรียญ",
    btn_challenges: "⚡ ชาเลนจ์",
    btn_top: "📊 พาร์ทเนอร์อันดับต้น",
    btn_back: "← ย้อนกลับ",
    btn_prev: "◀️ ก่อนหน้า",
    btn_next: "ถัดไป ▶️",
    stage: {
      invited: "ได้รับเชิญ",
      joined: "เข้าบอทแล้ว",
      active: "แอคทีฟ",
      booked: "จองแพ็กเกจ",
      paid: "ชำระแล้ว ✅",
      dormant: "ซาลง ⚠️",
      lost: "หายไป ⚫",
    },
  },
  team: {
    title: "👥 ทีมของฉัน",
    funnel_title: "ฟันเนล",
    funnel_line:
      "ทั้งหมด: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid} ⚠️{dormant} ⚫{lost}",
    next_title: "📌 งานทั้งหมดของวันนี้",
    next_heading: "📌 สิ่งที่ต้องทำวันนี้",
    next_empty: "โล่งแล้ว — ไม่มีงานค้าง พักจิบกาแฟก่อน ☕️",
    recent_heading: "🆕 สมาชิกใหม่ในทีม:",
    snooze_ok: "⏱️ เลื่อนออกไป 3 วัน",
    snooze_not_found: "งานปิดไปแล้วหรือไม่พบ",
    done_ok: "✅ เสร็จ",
    done_failed: "ไม่สำเร็จ — ลองใหม่อีกครั้ง",
    btn_done: "✅ {name}",
    btn_snooze: "⏱️",
    btn_all_actions: "📌 งานทั้งหมด",
    btn_ref_overview: "🤝 ลิงก์แนะนำ",
    btn_refresh: "🔄 รีเฟรช",
    reason: {
      invited_no_join_24h: "ไม่ได้เปิดบอทใน 24 ชั่วโมง — ส่งข้อความกระตุ้น",
      just_paid: "เพิ่งชำระ — แสดงความยินดีสักหน่อย 🎉",
      booked_silent_3d: "ผ่านไป 3 วันหลังจอง — ช่วยปิดการชำระ",
      active_silent_7d: "เงียบมา 7 วัน — ลองเช็กดูว่าเกิดอะไรขึ้น",
      winback_dormant: "ถึงเวลาดึงกลับ — ยังมีโอกาส",
      joined_no_activity_7d:
        "เข้ามาแต่ยังไม่ขยับ — ต้องช่วยออนบอร์ด",
    },
  },
  challenges: {
    title: "⚡ ชาเลนจ์พาร์ทเนอร์",
    active_heading: "กำลังดำเนินการ:",
    available_heading: "เปิดให้เริ่ม:",
    progress_line: "ความคืบหน้า: <b>{progress}/{goal}</b> · เหลือ {days} วัน",
    mark_active: "— กำลังทำ",
    mark_done: "— ✅ เสร็จแล้ว",
    btn_start: "▶️ เริ่ม: {title}",
    started_toast: "⚡ เริ่มชาเลนจ์แล้ว — ลุยเลย 🚀",
    start_failed_toast: "กำลังทำอยู่หรือยังไม่พร้อม",
    t: {
      invite_3_in_7d: "ชวน 3 คนภายใน 7 วัน",
      invite_5_in_14d: "ชวน 5 คนภายใน 14 วัน",
      invite_10_in_30d: "ชวน 10 คนภายใน 30 วัน",
    },
  },
  badges: {
    title: "🏆 เหรียญของฉัน",
    empty:
      "ยังไม่มีเหรียญ พาสมาชิกคนแรกที่จ่ายเงินเข้ามา — และปลดล็อก 🎉 «การชำระครั้งแรกในทีม»",
    first_paid: "🎉 การชำระครั้งแรกในทีม",
    partner_5: "⭐ พาร์ทเนอร์ 5+",
    partner_10: "🌟 พาร์ทเนอร์ 10+",
    partner_25: "💎 พาร์ทเนอร์ 25+",
    challenger_bronze: "🥉 เริ่มต้นรวดเร็ว",
    challenger_silver: "🥈 เติบโตมั่นคง",
    challenger_gold: "🥇 ผู้นำทีม",
  },
});

registerStrings("zh", {
  referral: {
    title: "🤝 你的合作伙伴链接",
    link_intro: "分享吧——每一位注册的人都让你的团队壮大：",
    stats_line:
      "团队：<b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid}",
    badges_line: "XP 与徽章：🏆 <b>{count}</b>",
    challenges_line: "⚡ 进行中的挑战：<b>{active}</b>",
    list_title: "📋 我的推荐",
    list_empty:
      "还没有人通过你的链接加入。分享给几位朋友——团队从这里开始 🚀",
    top_title: "📊 顶级合作伙伴（近 30 天）",
    top_empty: "排行榜还是空的。成为第一——邀请并登顶 🥇",
    btn_list: "📋 我的推荐",
    btn_badges: "🏆 徽章",
    btn_challenges: "⚡ 挑战",
    btn_top: "📊 顶级合作伙伴",
    btn_back: "← 返回",
    btn_prev: "◀️ 上一页",
    btn_next: "下一页 ▶️",
    stage: {
      invited: "已邀请",
      joined: "已进入机器人",
      active: "活跃",
      booked: "已预订套餐",
      paid: "已付款 ✅",
      dormant: "冷却 ⚠️",
      lost: "流失 ⚫",
    },
  },
  team: {
    title: "👥 我的团队",
    funnel_title: "漏斗",
    funnel_line:
      "总计：<b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid} ⚠️{dormant} ⚫{lost}",
    next_title: "📌 今天全部待办",
    next_heading: "📌 今日待办",
    next_empty: "清空啦——没有任务，喘口气 ☕️",
    recent_heading: "🆕 团队新成员：",
    snooze_ok: "⏱️ 已延后 3 天",
    snooze_not_found: "任务已关闭或未找到",
    done_ok: "✅ 完成",
    done_failed: "没成功——请再试一次",
    btn_done: "✅ {name}",
    btn_snooze: "⏱️",
    btn_all_actions: "📌 全部任务",
    btn_ref_overview: "🤝 推荐链接",
    btn_refresh: "🔄 刷新",
    reason: {
      invited_no_join_24h: "24 小时未打开机器人——发个提醒",
      just_paid: "刚刚付款——恭喜他 🎉",
      booked_silent_3d: "预订 3 天后——帮他完成付款",
      active_silent_7d: "7 天没动静——看看发生了什么",
      winback_dormant: "是时候把他拉回来——温和回归",
      joined_no_activity_7d:
        "进入了但一步未走——需要引导",
    },
  },
  challenges: {
    title: "⚡ 合作伙伴挑战",
    active_heading: "进行中：",
    available_heading: "可用：",
    progress_line: "进度：<b>{progress}/{goal}</b> · 剩余 {days} 天",
    mark_active: "— 进行中",
    mark_done: "— ✅ 已完成",
    btn_start: "▶️ 开始：{title}",
    started_toast: "⚡ 挑战已开始——冲 🚀",
    start_failed_toast: "已在进行或尚未可用",
    t: {
      invite_3_in_7d: "7 天内邀请 3 人",
      invite_5_in_14d: "14 天内邀请 5 人",
      invite_10_in_30d: "30 天内邀请 10 人",
    },
  },
  badges: {
    title: "🏆 我的徽章",
    empty:
      "还没有徽章。带来首位付款的队友——即可解锁 🎉「团队首笔付款」",
    first_paid: "🎉 团队首笔付款",
    partner_5: "⭐ 合作伙伴 5+",
    partner_10: "🌟 合作伙伴 10+",
    partner_25: "💎 合作伙伴 25+",
    challenger_bronze: "🥉 快速起步",
    challenger_silver: "🥈 稳步成长",
    challenger_gold: "🥇 团队领袖",
  },
});

registerStrings("en", {
  referral: {
    title: "🤝 Your partner link",
    link_intro: "Share it — every signup grows your team:",
    stats_line:
      "Team: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid}",
    badges_line: "XP & badges: 🏆 <b>{count}</b>",
    challenges_line: "⚡ Active challenges: <b>{active}</b>",
    list_title: "📋 My referrals",
    list_empty:
      "Nobody has joined through your link yet. Share it with a couple of friends — your team starts here 🚀",
    top_title: "📊 Top partners (last 30 days)",
    top_empty: "Leaderboard is empty. Be the first — invite and take the top 🥇",
    btn_list: "📋 My referrals",
    btn_badges: "🏆 Badges",
    btn_challenges: "⚡ Challenges",
    btn_top: "📊 Top partners",
    btn_back: "← Back",
    btn_prev: "◀️ Prev",
    btn_next: "Next ▶️",
    stage: {
      invited: "Invited",
      joined: "Joined the bot",
      active: "Active",
      booked: "Booked a plan",
      paid: "Paid ✅",
      dormant: "Cooled off ⚠️",
      lost: "Lost ⚫",
    },
  },
  team: {
    title: "👥 My team",
    funnel_title: "Funnel",
    funnel_line:
      "Total: <b>{total}</b> · 🔵{invited} 🟡{joined} 🔥{active} 📌{booked} ✅{paid} ⚠️{dormant} ⚫{lost}",
    next_title: "📌 All tasks for today",
    next_heading: "📌 What to do today",
    next_empty: "All clear — no open tasks. Take a breath ☕️",
    recent_heading: "🆕 Newest in your team:",
    snooze_ok: "⏱️ Snoozed for 3 days",
    snooze_not_found: "This task is already closed or not found",
    done_ok: "✅ Done",
    done_failed: "Didn't work — please try again",
    btn_done: "✅ {name}",
    btn_snooze: "⏱️",
    btn_all_actions: "📌 All tasks",
    btn_ref_overview: "🤝 Ref link",
    btn_refresh: "🔄 Refresh",
    reason: {
      invited_no_join_24h: "hasn't opened the bot in 24h — send a nudge",
      just_paid: "just paid — congratulate them 🎉",
      booked_silent_3d: "3 days after booking — help them close payment",
      active_silent_7d: "7 days of silence — check what's going on",
      winback_dormant: "time to win them back — a warm return is possible",
      joined_no_activity_7d:
        "joined but hasn't taken a single step — they need onboarding",
    },
  },
  challenges: {
    title: "⚡ Partner challenges",
    active_heading: "In progress:",
    available_heading: "Available:",
    progress_line: "Progress: <b>{progress}/{goal}</b> · {days} days left",
    mark_active: "— in progress",
    mark_done: "— ✅ completed",
    btn_start: "▶️ Start: {title}",
    started_toast: "⚡ Challenge started — let's go 🚀",
    start_failed_toast: "Already active or not available yet",
    t: {
      invite_3_in_7d: "Invite 3 people in 7 days",
      invite_5_in_14d: "Invite 5 people in 14 days",
      invite_10_in_30d: "Invite 10 people in 30 days",
    },
  },
  badges: {
    title: "🏆 My badges",
    empty:
      "No badges yet. Bring your first paying teammate — and you'll unlock 🎉 “First payment in team”",
    first_paid: "🎉 First payment in team",
    partner_5: "⭐ Partner 5+",
    partner_10: "🌟 Partner 10+",
    partner_25: "💎 Partner 25+",
    challenger_bronze: "🥉 Quick start",
    challenger_silver: "🥈 Steady growth",
    challenger_gold: "🥇 Team leader",
  },
});
